### ISSUE TITLE
Use getStaticProps for generation of files

### ISSUE THREAD

**Issue by Nautman** [sakerhetspolisen/portofolio#6]
Hi,

I think your website is really neat! A friendly tip is to use `getStaticProps` with NextJS. Then you won't have to have a loading screen on the "Work list". See more on data fetching here: https://nextjs.org/docs/basic-features/data-fetching

I really think this could be useful for your learning! If you have a hard time implementing this, you can ping me and I can help you out :)

**Comment by sakerhetspolisen** [comment]
Thanks for the feedback @Nautman ! I checked the Next docs and encountered a problem though. I use a custom _app-file for adding various SEO-related and font-related data in "head". The caveat is that combining a custom _app.tsx file with getStaticProps currently [isn't supported](https://nextjs.org/docs/advanced-features/custom-app#caveats). 

> App currently does not support Next.js Data Fetching methods like getStaticProps or getServerSideProps.

**Comment by sakerhetspolisen** [comment]
To use getStaticProps the _app.tsx file needs to be removed. In order for that to happen, the following things need to be fixed:

- The Bootstrap global CSS file  `bootstrap.min.css`  needs to be imported elsewhere
- The FontAwesome global CSS file `fontawesome-svg-core/styles.css` needs to be imported elsewhere
- The global CSS file `global.css` needs to be imported elsewhere
- The ApolloClient needs to be initialized elsewhere (possible since the GraphQL API is only used on the /work page)

That brings up a question: **Is it even possible to use packages that require global CSS without an _app.jsx/tsx file?**

**Comment by Nautman** [comment]
Quick question, you haven't tried creating `getStaticProps` on one page, just for the sake of testing?

I think almost all NextJS projects have a `_app.tsx` file. I do, and `getStaticProps` still works for me.

EDIT: I just want to say that I haven't really had the time to read and understand the link to the documentation that you linked, so if the answer to my question / thinking is there then you don't really need to respond explain it here to me :)

**Comment by sakerhetspolisen** [comment]
Fixed in #7

**Comment by Nautman** [comment]
Cool! :D
